apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-cicd
  labels:
    app: node-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-cicd
  template:
    metadata:
      labels:
        app: node-cicd
    spec:
      containers:
      - name: node-cicd
        image: mdiakhate12/node-cicd:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: node-cicd
spec:
  type: NodePort
  selector:
    app: node-cicd
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30080
